#' plot_png_pdf
#' A helper function to save figures generated by the app in png or pdf formats
#' @param plot the plot to be saved to an external file
#' @param file_name output file name
#' @param image_format output file format: pdf or png
#' @param height the height of output image: inches for pdf; pixels for png
#' @param width the width of output image: inches for pdf; pixels for png
#'
#' @return
#' @export
#'
#' @examples
#' \dontrun{
#' plot_png_pdf(plot = ggplot2_obj, file_name = "out_file.pdf", height = 7, width = 7, image_format = "pdf")
#' }
plot_png_pdf <- function(plot, file_name, image_format = c("png","pdf"), height = 4, width = 4) {
  # evaluate input type:
  image_format <- match.arg(image_format)
  
  if (image_format == "png") {
    png(file_name,
        height = height,
        width = width
    )
    plot(plot)
    dev.off()
  } else {
    pdf(file_name,
        height = height,
        width = width
    )
    plot(plot)
    dev.off()
  }
}